services:
  api:
    build:
      context: ./
      target: dev
    container_name: api
    ports:
      - 3030:3030
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: db
    env_file:
      - .env
    ports:
      - 5432:5432
